// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package source

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ConfigConnectionString = "connectionString"
	ConfigContainerName    = "containerName"
	ConfigMaxResults       = "maxResults"
	ConfigPollingPeriod    = "pollingPeriod"
)

func (Config) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ConfigConnectionString: {
			Default:     "",
			Description: "The Azure Storage connection string.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigContainerName: {
			Default:     "",
			Description: "The name of the container to monitor.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		ConfigMaxResults: {
			Default:     "5000",
			Description: "The maximum number of items, per page, when reading container's items.",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: 0},
				config.ValidationLessThan{V: 5001},
			},
		},
		ConfigPollingPeriod: {
			Default:     "1s",
			Description: "The polling period for the CDC mode, formatted as a time.Duration string.",
			Type:        config.ParameterTypeDuration,
			Validations: []config.Validation{},
		},
	}
}
